name: Genereer RSS feed uit JSON

on:
  push:
    paths:
      - 'data/meterstanden.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Haal repo op
      uses: actions/checkout@v3

    - name: Installeer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Genereer RSS feed
      run: python3 scripts/genereer_rss.py

    - name: Commit en push RSS feed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add meterstanden-dagelijks.xml
        git commit -m "Update RSS feed"
        git push
