name: Verwerk nieuwe meterstand

on:
  push:
    paths:
      - 'data/nieuwe-meterstand.json'

jobs:
  verwerk:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installeer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installeer vereisten (indien nodig)
        run: pip install -r requirements.txt || echo "Geen requirements nodig"

      - name: Voer verwerk_meterstand.py uit
        run: python scripts/verwerk_meterstand.py

      - name: Commit en push gewijzigde bestanden
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🧾 Verwerkte nieuwe meterstand en geüpdatet RSS-feed'
          file_pattern: 'data/meterstanden.json meterstanden-dagelijks.xml'
